services:
  payments-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_api
    restart: on-failure
    ports:
      - "5109:8080" 
    environment:
      RABBITMQ_HOST: rabbitmq
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      Jwt__Key: ${Jwt__Key}
    networks:
      - microsservicos-net

networks:
  microsservicos-net:
    name: app-network
    driver: bridge