apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: fiapstore
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  RABBITMQ_HOST: "rabbitmq"
  UsersApi__BaseUrl: "http://users-api:8080/"
  DynamoDb__LogTableName: "payments-logs"
  DynamoDb__UseLocal: "false"
  DynamoDb__Region: "us-east-2"
